### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by marcosvkp** [PocketEssential/OneInTheChamber#1]
How to join in PocketEssential?
Como posso entrar para PocketEssential? :P

**Comment by xZeroMCPE** [comment]
@RedstoneAlmeida Know what your doing when it comes to PHP + Developer etc. Make quality stuffs etc.

And request to be invited in the group. If you think you're up for the challenge!

**Comment by ghost** [comment]
@RedstoneAlmeida You should make a standalone and unique plugin
