### ISSUE TITLE
W ITALIA

### ISSUE THREAD

**Issue by JackDiSpade21** [PocketEssential/OneInTheChamber#3]
I am not English and I don't know the language very good. I can't find anything useful in the readme.md
Please don't insult me. I can't understand what you wanted to tell. What I need to watch? How do I enable the plugin?
P.S: Sorry for my bad English
P.P.S: And I am not a good developer I'm just practising php . Sorry, again.

**Comment by xZeroMCPE** [comment]
What language do you speak? natively

**Comment by JackDiSpade21** [comment]
Italian

**Comment by xZeroMCPE** [comment]
Oh, perché non l'hai detto prima!

**Comment by JackDiSpade21** [comment]
Oddio che felicità

**Comment by JackDiSpade21** [comment]
Voglio solo dirti che sei un grande

**Comment by JackDiSpade21** [comment]
Se per favore dici al tuo amico di calmare i toni e di evitare di insultare,mi faresti un favore grandissimo, non ho capito come usare questo plugin

**Comment by JackDiSpade21** [comment]
Cioè so cosa è One In The Chamber ma se guardi nelle "Issues" chiuse vedrai che non mi parte il plugin

**Comment by JackDiSpade21** [comment]
Poi ti volevo chiedere se puoi darmi il tuo kik , ho tante cose di dirti è da chiederti

**Comment by xZeroMCPE** [comment]
Ho kik ma non mi piace, ma ancora una volta. Hai skype? ma se poi non kik sarebbe bene per me

**Comment by iTzSilver** [comment]
Ma il plugin è finito?

**Comment by xZeroMCPE** [comment]
Non ha ancora alcune cose che deve essere fatto! Per quanto riguarda questo repo quotidianamente e si comunica malato quando è :)

**Comment by iTzSilver** [comment]
Ma sei Italiano? Lo parli un po male xD

**Comment by JackDiSpade21** [comment]
No, purtroppo ho un PC fisso di qualche anno fa, hai kik no? Spero che mi risponderai presto xD

**Comment by xZeroMCPE** [comment]
Sì, è necessario scaricare Skype sul vostro tavolo! la sua reallly buona

**Comment by JackDiSpade21** [comment]
Non ho capito

**Comment by JackDiSpade21** [comment]
Sei sicuro di essere italiano?

**Comment by iTzSilver** [comment]
Qualcosa mi dice che usa google translate xD
Rainbow ma programmi plugin?

**Comment by JackDiSpade21** [comment]
Si ma nel tempo libero (mai xD)

**Comment by xZeroMCPE** [comment]
-__- Veramente?

**Comment by JackDiSpade21** [comment]
Cosa?

**Comment by JackDiSpade21** [comment]
@SilverGamers89  rispondimi nel tuo Plugin xD Ho bisogno di aiuti e di aiutare
